# Make all rendered pages use the default theme by default.
# Additionally, let scripts be defined but empty.
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      scripts:



discord: https://discord.gg/ymb84qM54A
github: https://github.com/oscie57
email: mailto:me@oscie.net

ecdpdiscord: https://discord.gg/3MkYyFnkqG
