# Make all rendered pages use the default theme by default.
# Additionally, let scripts be defined but empty.
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      scripts:




# Site Links
discord: https://discord.gg/ymb84qM54A
github: https://github.com/oscie57
email: mailto:vocaloid@oscie.net
mastodon: https://wetdry.world/@oscie_p

# Vocaloid Links
youtube: https://www.youtube.com/playlist?list=PLjNyFGsiYbO7k4vF4ahw_IYJVH4UHyGwy
niconico: https://nicovideo.jp/series/409195
twitter: https://twitter.com/oscie_p
